CREATE TABLE `measurements` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`customerName` varchar(255),
	`notes` text,
	`imageKey` text,
	`imageUrl` text,
	`imageWidth` int,
	`imageHeight` int,
	`pointsJson` json,
	`leftFootLength` float,
	`rightFootLength` float,
	`leftFootWidth` float,
	`rightFootWidth` float,
	`leftHeelToMp` float,
	`rightHeelToMp` float,
	`regressionResultJson` json,
	`status` enum('draft','completed') NOT NULL DEFAULT 'draft',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `measurements_id` PRIMARY KEY(`id`)
);
